(el-get 'sync '(go-mode-github))
(el-get 'sync '(go-autocomplete))
(require 'go-autocomplete)
(require 'auto-complete-config)
(add-hook 'go-mode-hook
          '(lambda ()
             (setq c-basic-offset 4)
             (setq indent-tabs-mode t)
             (local-set-key (kbd "M-.") 'godef-jump)
             (local-set-key (kbd "C-c C-r") 'go-remove-unused-imports)
             (local-set-key (kbd "C-c i") 'go-goto-imports)
             (local-set-key (kbd "C-c d") 'godoc)
             (define-key ac-mode-map (kbd "M-TAB") 'auto-complete)))
(add-hook 'before-save-hook 'gofmt-before-save)
(add-to-list 'ac-modes 'go-mode)
